import { useState, useRef, useEffect } from 'react'
import { useDesktopStore } from '../../store/windowStore'
import { getMediaBaseUrl } from '../../data/mediaBaseUrl'

interface Track {
  title: string
  album: string
  artist: string
  src: string
  cover: string | null
}

export default function MusicPlayer({ windowId }: { windowId: string }) {
  const audioRef = useRef<HTMLAudioElement>(null)
  const [playlist, setPlaylist] = useState<Track[]>([])
  const [currentIdx, setCurrentIdx] = useState(0)
  const [playing, setPlaying] = useState(false)
  const [progress, setProgress] = useState(0)
  const [duration, setDuration] = useState(0)
  const [volume, setVolume] = useState(0.7)
  const [loaded, setLoaded] = useState(false)
  const initialDataHandled = useRef(false)

  // Import window store to read initialData
  const win = useDesktopStore(s => s.windows.find(w => w.id === windowId))

  // Auto-load playlist from media manifest generated by vite plugin
  useEffect(() => {
    const base = getMediaBaseUrl()
    fetch('/media-manifest.json')
      .then(r => r.json())
      .then((data: { music: Track[] }) => {
        if (data.music && data.music.length > 0) {
          // Prefix external base URL to media paths
          const prefixed = data.music.map(t => ({
            ...t,
            src: base + t.src,
            cover: t.cover ? base + t.cover : null,
          }))
          setPlaylist(prefixed)
        }
        setLoaded(true)
      })
      .catch(() => setLoaded(true))
  }, [])

  // Handle initialData to auto-play a specific track
  useEffect(() => {
    if (!loaded || playlist.length === 0 || !win?.initialData?.playSrc) return
    const src = win.initialData.playSrc as string
    // Find matching track by src path
    const idx = playlist.findIndex(t => t.src === src)
    if (idx >= 0 && (idx !== currentIdx || !initialDataHandled.current)) {
      initialDataHandled.current = true
      setCurrentIdx(idx)
      setPlaying(false)
      setProgress(0)
      setDuration(0)
      setTimeout(() => {
        if (playlist[idx]?.src) {
          audioRef.current?.play()
          setPlaying(true)
        }
      }, 150)
    }
  }, [loaded, playlist, win?.initialData])

  const current = playlist[currentIdx]

  // Audio event listeners
  useEffect(() => {
    const audio = audioRef.current
    if (!audio) return
    const onTime = () => setProgress(audio.currentTime)
    const onDur = () => setDuration(audio.duration || 0)
    const onEnd = () => {
      if (currentIdx < playlist.length - 1) {
        setCurrentIdx(i => i + 1)
        setTimeout(() => { audioRef.current?.play(); setPlaying(true) }, 100)
      } else {
        setPlaying(false)
      }
    }
    audio.addEventListener('timeupdate', onTime)
    audio.addEventListener('loadedmetadata', onDur)
    audio.addEventListener('ended', onEnd)
    return () => {
      audio.removeEventListener('timeupdate', onTime)
      audio.removeEventListener('loadedmetadata', onDur)
      audio.removeEventListener('ended', onEnd)
    }
  }, [currentIdx, playlist.length])

  useEffect(() => {
    if (audioRef.current) audioRef.current.volume = volume
  }, [volume])

  const togglePlay = () => {
    if (!current?.src) return
    if (playing) { audioRef.current?.pause(); setPlaying(false) }
    else { audioRef.current?.play(); setPlaying(true) }
  }

  const seek = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = parseFloat(e.target.value)
    if (audioRef.current) audioRef.current.currentTime = val
    setProgress(val)
  }

  const selectTrack = (i: number) => {
    setCurrentIdx(i)
    setPlaying(false)
    setProgress(0)
    setDuration(0)
    setTimeout(() => {
      if (playlist[i]?.src) {
        audioRef.current?.play()
        setPlaying(true)
      }
    }, 150)
  }

  const prev = () => { if (currentIdx > 0) selectTrack(currentIdx - 1) }
  const next = () => { if (currentIdx < playlist.length - 1) selectTrack(currentIdx + 1) }
  const fmt = (s: number) => {
    if (!isFinite(s)) return '0:00'
    const m = Math.floor(s / 60)
    const sec = Math.floor(s % 60)
    return `${m}:${sec.toString().padStart(2, '0')}`
  }

  return (
    <div className="wmp-app">
      <audio ref={audioRef} src={current?.src || undefined} />

      {/* Album art / Visualizer area */}
      <div className="wmp-visualizer">
        {current?.cover ? (
          <>
            {/* Blurred background */}
            <img src={current.cover} alt="" className="wmp-album-bg" />
            {/* Sharp centered cover */}
            <img src={current.cover} alt={current.album} className="wmp-album-front" />
          </>
        ) : (
          <div className="wmp-viz-bg">
            {playing && Array.from({ length: 16 }).map((_, i) => (
              <div key={i} className="wmp-viz-bar" style={{
                animationDelay: `${i * 0.05}s`,
              }} />
            ))}
          </div>
        )}
        <div className="wmp-now-playing">
          <div className="wmp-title">{current?.title || (loaded ? 'No tracks' : 'Loading...')}</div>
          <div className="wmp-artist">
            {current ? `${current.artist} — ${current.album}` : ''}
          </div>
        </div>
      </div>

      {/* Transport controls */}
      <div className="wmp-controls">
        <div className="wmp-progress-row">
          <span className="wmp-time">{fmt(progress)}</span>
          <input type="range" className="wmp-slider" min={0} max={duration || 1} step={0.1} value={progress} onChange={seek} />
          <span className="wmp-time">{fmt(duration)}</span>
        </div>
        <div className="wmp-buttons">
          <button className="wmp-btn" onClick={prev} title="Previous">⏮</button>
          <button className="wmp-btn wmp-play-btn" onClick={togglePlay} title={playing ? 'Pause' : 'Play'}>
            {playing ? '⏸' : '▶'}
          </button>
          <button className="wmp-btn" onClick={next} title="Next">⏭</button>
          <button className="wmp-btn" onClick={() => {
            if (audioRef.current) { audioRef.current.pause(); audioRef.current.currentTime = 0 }
            setPlaying(false); setProgress(0)
          }} title="Stop">⏹</button>
          <div style={{ flex: 1 }} />
          <span style={{ fontSize: 10, color: '#aaa', marginRight: 4 }}>Vol</span>
          <input type="range" className="wmp-vol" min={0} max={1} step={0.05} value={volume}
            onChange={e => setVolume(parseFloat(e.target.value))} />
        </div>
      </div>

      {/* Playlist */}
      <div className="wmp-playlist">
        <div className="wmp-playlist-header">
          Playlist — {playlist.length} track{playlist.length !== 1 ? 's' : ''}
        </div>
        {!loaded && <div className="wmp-playlist-empty">Loading...</div>}
        {loaded && playlist.length === 0 && (
          <div className="wmp-playlist-empty">
            <p>No music found.</p>
            <p style={{ fontSize: 10, color: '#666', marginTop: 4 }}>
              Add .mp3 files to <code>public/music/SongName/AlbumName/ArtistName.mp3</code>
            </p>
            <p style={{ fontSize: 10, color: '#666' }}>
              Add album covers as <code>.png</code> with the same path/name.
            </p>
          </div>
        )}
        {playlist.map((track, i) => (
          <div
            key={i}
            className={`wmp-playlist-item ${i === currentIdx ? 'active' : ''}`}
            onClick={() => selectTrack(i)}
          >
            {track.cover ? (
              <img src={track.cover} alt="" className="wmp-playlist-thumb" />
            ) : (
              <div className="wmp-playlist-thumb-placeholder">♪</div>
            )}
            <div className="wmp-playlist-info">
              <span className="wmp-track-title">{track.title}</span>
              <span className="wmp-track-artist">{track.artist} — {track.album}</span>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
