import { useState, useRef, useEffect } from 'react'
import { useDesktopStore } from '../../store/windowStore'
import { getMediaBaseUrl } from '../../data/mediaBaseUrl'

interface Video {
  title: string
  src: string
  cover: string | null
}

export default function VideoPlayer({ windowId }: { windowId: string }) {
  const videoRef = useRef<HTMLVideoElement>(null)
  const [videos, setVideos] = useState<Video[]>([])
  const [currentIdx, setCurrentIdx] = useState(-1)
  const [playing, setPlaying] = useState(false)
  const [loaded, setLoaded] = useState(false)
  const [videoError, setVideoError] = useState<string | null>(null)
  const initialDataHandled = useRef(false)

  // Import window store to read initialData
  const win = useDesktopStore(s => s.windows.find(w => w.id === windowId))

  // Auto-load from media manifest generated by vite plugin
  useEffect(() => {
    const base = getMediaBaseUrl()
    fetch('/media-manifest.json')
      .then(r => r.json())
      .then((data: { videos: Video[] }) => {
        if (data.videos && data.videos.length > 0) {
          // Prefix external base URL to media paths
          const prefixed = data.videos.map(v => ({
            ...v,
            src: base + v.src,
            cover: v.cover ? base + v.cover : null,
          }))
          setVideos(prefixed)
        }
        setLoaded(true)
      })
      .catch(() => setLoaded(true))
  }, [])

  // Handle initialData to auto-play a specific video
  useEffect(() => {
    if (!loaded || videos.length === 0 || !win?.initialData?.playSrc) return
    const src = win.initialData.playSrc as string
    const idx = videos.findIndex(v => v.src === src)
    if (idx >= 0 && (idx !== currentIdx || !initialDataHandled.current)) {
      initialDataHandled.current = true
      selectVideo(idx)
    }
  }, [loaded, videos, win?.initialData])

  const current = currentIdx >= 0 ? videos[currentIdx] : null

  const selectVideo = (i: number) => {
    setCurrentIdx(i)
    setPlaying(false)
    setVideoError(null)
    // Let the video element load the new source, then attempt play
    setTimeout(() => {
      const el = videoRef.current
      if (!videos[i]?.src || !el) return
      el.load()
      el.play().catch(() => { /* handled by onError */ })
    }, 100)
  }

  const handleVideoError = () => {
    const src = current?.src || ''
    if (src.endsWith('.avi')) {
      setVideoError(
        'AVI files are not natively supported by browsers. ' +
        'Convert to .mp4 (H.264) or .webm (VP9) for reliable playback. ' +
        'Use FFmpeg: ffmpeg -i movie.avi -c:v libx264 -c:a aac movie.mp4'
      )
    } else {
      setVideoError(
        'This video could not be played. The format may not be supported by your browser, ' +
        'or the file may be too large to stream. Try converting to .mp4 (H.264).'
      )
    }
    setPlaying(false)
  }

  return (
    <div className="vp-app">
      {/* Video Screen */}
      <div className="vp-screen">
        {current?.src ? (
          <>
            <video
              ref={videoRef}
              src={current.src}
              className="vp-video"
              controls
              preload="auto"
              onPlay={() => { setPlaying(true); setVideoError(null) }}
              onPause={() => setPlaying(false)}
              onError={handleVideoError}
              onCanPlay={() => setVideoError(null)}
            />
            {videoError && (
              <div className="vp-error-overlay">
                <div className="vp-error-icon">⚠️</div>
                <p className="vp-error-text">{videoError}</p>
              </div>
            )}
          </>
        ) : (
          <div className="vp-placeholder">
            <div style={{ fontSize: 48, opacity: 0.3 }}>🎬</div>
            <p>{loaded ? 'Select a movie below' : 'Loading...'}</p>
            {loaded && videos.length === 0 && (
              <p style={{ fontSize: 10, color: '#666', maxWidth: 300 }}>
                No videos found. Add .mp4 or .webm files to <code>public/videos/MovieName.mp4</code><br />
                Add covers as <code>MovieName.png</code> in the same folder.<br />
                <strong>Note:</strong> .avi files need conversion to .mp4 for browser playback.
              </p>
            )}
          </div>
        )}
      </div>

      {/* Transport controls */}
      <div className="vp-controls">
        <button className="wmp-btn" onClick={() => currentIdx > 0 && selectVideo(currentIdx - 1)} title="Previous">⏮</button>
        <button className="wmp-btn wmp-play-btn" onClick={() => {
          if (!current?.src) return
          if (playing) { videoRef.current?.pause(); setPlaying(false) }
          else { videoRef.current?.play()?.catch(() => {}); setPlaying(true) }
        }} title={playing ? 'Pause' : 'Play'}>
          {playing ? '⏸' : '▶'}
        </button>
        <button className="wmp-btn" onClick={() => currentIdx < videos.length - 1 && selectVideo(currentIdx + 1)} title="Next">⏭</button>
        <span style={{ fontSize: 11, color: '#ccc', marginLeft: 8, flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
          {current?.title || 'No video selected'}
        </span>
      </div>

      {/* Movie grid with covers */}
      <div className="vp-movie-grid">
        {!loaded && <div className="wmp-playlist-empty">Loading...</div>}
        {loaded && videos.length === 0 && (
          <div className="wmp-playlist-empty" style={{ padding: 16, textAlign: 'center', width: '100%' }}>
            No movies found.
          </div>
        )}
        {videos.map((v, i) => {
          const isAvi = v.src.endsWith('.avi')
          return (
            <div
              key={i}
              className={`vp-movie-card ${i === currentIdx ? 'active' : ''}`}
              onClick={() => selectVideo(i)}
            >
              {v.cover ? (
                <img src={v.cover} alt={v.title} className="vp-movie-cover" />
              ) : (
                <div className="vp-movie-cover-placeholder">🎬</div>
              )}
              <div className="vp-movie-title">
                {v.title}{isAvi && <span className="vp-avi-badge"> (AVI)</span>}
              </div>
            </div>
          )
        })}
      </div>
    </div>
  )
}
